package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstMovimentacao generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "seq_movimentacao", sequenceName = "seq_movimentacao", allocationSize = 1)
public class EstMovimentacao implements java.io.Serializable {

    private int movId;
    private CarEstTipoOperacao carEstTipoOperacao;
    private EstProduto estProduto;
    private Date movData;
    private double movQuantidade;
    private double movVlrUnit;
    private double movTotal;

    public EstMovimentacao() {
    }

    public EstMovimentacao(int movId, Date movData, double movQuantidade, double movVlrUnit, double movTotal) {
        this.movId = movId;
        this.movData = movData;
        this.movQuantidade = movQuantidade;
        this.movVlrUnit = movVlrUnit;
        this.movTotal = movTotal;
    }

    public EstMovimentacao(int movId, CarEstTipoOperacao carEstTipoOperacao, EstProduto estProduto, Date movData, double movQuantidade, double movVlrUnit, double movTotal) {
        this.movId = movId;
        this.carEstTipoOperacao = carEstTipoOperacao;
        this.estProduto = estProduto;
        this.movData = movData;
        this.movQuantidade = movQuantidade;
        this.movVlrUnit = movVlrUnit;
        this.movTotal = movTotal;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_movimentacao")
    public int getMovId() {
        return this.movId;
    }

    public void setMovId(int movId) {
        this.movId = movId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    public CarEstTipoOperacao getCarEstTipoOperacao() {
        return this.carEstTipoOperacao;
    }

    public void setCarEstTipoOperacao(CarEstTipoOperacao carEstTipoOperacao) {
        this.carEstTipoOperacao = carEstTipoOperacao;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    public EstProduto getEstProduto() {
        return this.estProduto;
    }

    public void setEstProduto(EstProduto estProduto) {
        this.estProduto = estProduto;
    }

    @Temporal(TemporalType.DATE)
    public Date getMovData() {
        return this.movData;
    }

    public void setMovData(Date movData) {
        this.movData = movData;
    }

    public double getMovQuantidade() {
        return this.movQuantidade;
    }

    public void setMovQuantidade(double movQuantidade) {
        this.movQuantidade = movQuantidade;
    }

    public double getMovVlrUnit() {
        return this.movVlrUnit;
    }

    public void setMovVlrUnit(double movVlrUnit) {
        this.movVlrUnit = movVlrUnit;
    }

    public double getMovTotal() {
        return this.movTotal;
    }

    public void setMovTotal(double movTotal) {
        this.movTotal = movTotal;
    }

}
