package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;

/**
 * FlxcxOperacoes generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "seq_opCodigo", sequenceName = "seq_opCodigo",
        allocationSize = 1)
public class FlxcxOperacoes implements java.io.Serializable {

    private int opCodigo;
    private String opDescricao;
    private Set<CarCapContas> carCapContass = new HashSet(0);
    private FlxcxEspecificacoes flxcxEspecificacoes;

    public FlxcxOperacoes() {
    }

    public FlxcxOperacoes(int opCodigo) {
        this.opCodigo = opCodigo;
    }

    public FlxcxOperacoes(int opCodigo, String opDescricao, Set<CarCapContas> carCapContass) {
        this.opCodigo = opCodigo;
        this.opDescricao = opDescricao;
        this.carCapContass = carCapContass;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_opCodigo")
    public int getOpCodigo() {
        return this.opCodigo;
    }

    public void setOpCodigo(int opCodigo) {
        this.opCodigo = opCodigo;
    }

    public String getOpDescricao() {
        return this.opDescricao;
    }

    public void setOpDescricao(String opDescricao) {
        this.opDescricao = opDescricao;
    }

    @OneToMany(mappedBy = "flxcxOperacoes")
    public Set<CarCapContas> getCarCapContass() {
        return carCapContass;
    }

    public void setCarCapContass(Set<CarCapContas> carCapContass) {
        this.carCapContass = carCapContass;
    }

    @ManyToOne
    public FlxcxEspecificacoes getFlxcxEspecificacoes() {
        return flxcxEspecificacoes;
    }

    public void setFlxcxEspecificacoes(FlxcxEspecificacoes flxcxEspecificacoes) {
        this.flxcxEspecificacoes = flxcxEspecificacoes;
    }

}
