package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * FlxcxEspecificacoes generated by hbm2java
 */
@Entity
public class FlxcxEspecificacoes implements java.io.Serializable {

    private int espCodigo;
    private String espDescricao;
    private Integer espCodigoPai;
    private List<FlxcxOperacoes> operacao;

    public FlxcxEspecificacoes() {
    }

    public FlxcxEspecificacoes(int espCodigo) {
        this.espCodigo = espCodigo;
    }

    public FlxcxEspecificacoes(int espCodigo, String espDescricao, Integer espCodigoPai) {
        this.espCodigo = espCodigo;
        this.espDescricao = espDescricao;
        this.espCodigoPai = espCodigoPai;
    }

    @Id
    public int getEspCodigo() {
        return this.espCodigo;
    }

    public void setEspCodigo(int espCodigo) {
        this.espCodigo = espCodigo;
    }

    public String getEspDescricao() {
        return this.espDescricao;
    }

    public void setEspDescricao(String espDescricao) {
        this.espDescricao = espDescricao;
    }

    public Integer getEspCodigoPai() {
        return this.espCodigoPai;
    }

    public void setEspCodigoPai(Integer espCodigoPai) {
        this.espCodigoPai = espCodigoPai;
    }

    @OneToMany(mappedBy = "flxcxEspecificacoes")
    public List<FlxcxOperacoes> getOperacao() {
        return operacao;
    }

    public void setOperacao(List<FlxcxOperacoes> operacao) {
        this.operacao = operacao;
    }

}
