
package contasPagar;

/**
 *
 * @author dimhr12
 */
public class TelaCadastrarConta extends javax.swing.JFrame {

   
    public TelaCadastrarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextCadConta = new javax.swing.JLabel();
        TextCredor = new javax.swing.JLabel();
        ComboBoxPessoa = new javax.swing.JComboBox<>();
        btnCadastrarPessoa = new javax.swing.JButton();
        TextValorConta = new javax.swing.JLabel();
        FieldValorConta = new javax.swing.JTextField();
        TextData = new javax.swing.JLabel();
        TextNumParc = new javax.swing.JLabel();
        FieldNumParc = new javax.swing.JTextField();
        TextNota = new javax.swing.JLabel();
        ComboBoxNotaFiscal = new javax.swing.JComboBox<>();
        btnCadastrarNota = new javax.swing.JButton();
        TextValorPago = new javax.swing.JLabel();
        FieldValorPago = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        DateChooserEmissao = new com.toedter.calendar.JDateChooser();
        PainelParcelas = new javax.swing.JPanel();
        TextPainelParcelas = new javax.swing.JLabel();
        TextVencimentoParc = new javax.swing.JLabel();
        DateChooserVencParc = new com.toedter.calendar.JDateChooser();
        TextPgtoParcelas = new javax.swing.JLabel();
        DateChooserPgtoParc = new com.toedter.calendar.JDateChooser();
        TextAcrescimos = new javax.swing.JLabel();
        FieldAcrescimos = new javax.swing.JTextField();
        TextContaDebito = new javax.swing.JLabel();
        ComboBoxContaDebito = new javax.swing.JComboBox<>();
        TextValorParcela = new javax.swing.JLabel();
        FieldValorParcela = new javax.swing.JTextField();
        TextValorPagoParc = new javax.swing.JLabel();
        FieldValorPagoParc = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextCadConta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TextCadConta.setText("CADASTRAR CONTA A PAGAR");

        TextCredor.setText("1. Credor: Selecione da lista ou cadastre um novo");

        ComboBoxPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alibem", "João", "José", "Empresa Compradora de Leite" }));
        ComboBoxPessoa.setToolTipText("");
        ComboBoxPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPessoaActionPerformed(evt);
            }
        });

        btnCadastrarPessoa.setText("Cadastrar Pessoa");
        btnCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPessoaActionPerformed(evt);
            }
        });

        TextValorConta.setText("3. Valor da conta:");

        FieldValorConta.setText("R$");
        FieldValorConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldValorContaFocusGained(evt);
            }
        });
        FieldValorConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldValorContaMouseClicked(evt);
            }
        });

        TextData.setText("2. Data de Emissão:");

        TextNumParc.setText("4. Número de Parcelas: ");

        FieldNumParc.setText("N° de parcelas");
        FieldNumParc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldNumParcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldNumParcFocusLost(evt);
            }
        });
        FieldNumParc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldNumParcMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FieldNumParcMouseExited(evt);
            }
        });
        FieldNumParc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldNumParcKeyReleased(evt);
            }
        });

        TextNota.setText("5. Nota fiscal vinculada: Selecione da lista ou cadastre uma nova");

        ComboBoxNotaFiscal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nota Fiscal 1", "Nota Fiscal 2", "Nota Fiscal 3", "Nota Fiscal 4" }));

        btnCadastrarNota.setText("Cadastrar Nota Fiscal");

        TextValorPago.setText("6. Valor pago: Informe caso a conta tenha sido paga total ou parcialmente");

        FieldValorPago.setText("R$");
        FieldValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldValorPagoFocusGained(evt);
            }
        });
        FieldValorPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldValorPagoMouseClicked(evt);
            }
        });

        btnFinalizar.setText("Finalizar");

        PainelParcelas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PainelParcelas.setEnabled(false);

        TextPainelParcelas.setText("Parcelas da conta: Preencha as informações abaixo");
        TextPainelParcelas.setEnabled(false);

        TextVencimentoParc.setText("1. Data de vencimento:");
        TextVencimentoParc.setEnabled(false);

        DateChooserVencParc.setEnabled(false);

        TextPgtoParcelas.setText("2. Data de pagamento:");
        TextPgtoParcelas.setEnabled(false);

        DateChooserPgtoParc.setEnabled(false);

        TextAcrescimos.setText("3. Acréscimos:");
        TextAcrescimos.setEnabled(false);

        FieldAcrescimos.setText("R$");
        FieldAcrescimos.setEnabled(false);
        FieldAcrescimos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldAcrescimosFocusGained(evt);
            }
        });
        FieldAcrescimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldAcrescimosMouseClicked(evt);
            }
        });

        TextContaDebito.setText("4. Conta de débito:");
        TextContaDebito.setEnabled(false);

        ComboBoxContaDebito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxContaDebito.setEnabled(false);

        TextValorParcela.setText("5. Valor da parcela:");
        TextValorParcela.setEnabled(false);

        FieldValorParcela.setText("R$");
        FieldValorParcela.setEnabled(false);
        FieldValorParcela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldValorParcelaFocusGained(evt);
            }
        });
        FieldValorParcela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldValorParcelaMouseClicked(evt);
            }
        });

        TextValorPagoParc.setText("6. Valor Pago:");
        TextValorPagoParc.setEnabled(false);

        FieldValorPagoParc.setText("R$");
        FieldValorPagoParc.setEnabled(false);
        FieldValorPagoParc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldValorPagoParcFocusGained(evt);
            }
        });
        FieldValorPagoParc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldValorPagoParcMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelParcelasLayout = new javax.swing.GroupLayout(PainelParcelas);
        PainelParcelas.setLayout(PainelParcelasLayout);
        PainelParcelasLayout.setHorizontalGroup(
            PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelParcelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextPainelParcelas)
                    .addGroup(PainelParcelasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelParcelasLayout.createSequentialGroup()
                                .addComponent(TextPgtoParcelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DateChooserPgtoParc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelParcelasLayout.createSequentialGroup()
                                .addComponent(TextVencimentoParc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DateChooserVencParc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelParcelasLayout.createSequentialGroup()
                                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelParcelasLayout.createSequentialGroup()
                                        .addComponent(TextContaDebito)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxContaDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelParcelasLayout.createSequentialGroup()
                                        .addComponent(TextAcrescimos)
                                        .addGap(18, 18, 18)
                                        .addComponent(FieldAcrescimos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelParcelasLayout.createSequentialGroup()
                                        .addComponent(TextValorParcela)
                                        .addGap(18, 18, 18)
                                        .addComponent(FieldValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelParcelasLayout.createSequentialGroup()
                                        .addComponent(TextValorPagoParc)
                                        .addGap(18, 18, 18)
                                        .addComponent(FieldValorPagoParc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelParcelasLayout.setVerticalGroup(
            PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelParcelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextPainelParcelas)
                .addGap(18, 18, 18)
                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextVencimentoParc)
                    .addComponent(DateChooserVencParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextPgtoParcelas)
                    .addComponent(DateChooserPgtoParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextAcrescimos)
                    .addComponent(FieldAcrescimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextContaDebito)
                    .addComponent(ComboBoxContaDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextValorParcela)
                    .addComponent(FieldValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextValorPagoParc)
                    .addComponent(FieldValorPagoParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextCadConta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextData)
                                .addGap(18, 18, 18)
                                .addComponent(DateChooserEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextValorConta)
                                .addGap(18, 18, 18)
                                .addComponent(FieldValorConta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnCadastrarPessoa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextNumParc)
                                .addGap(18, 18, 18)
                                .addComponent(FieldNumParc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextCredor)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(PainelParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextNota)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ComboBoxNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(btnCadastrarNota))
                                            .addComponent(TextValorPago)
                                            .addComponent(FieldValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(btnFinalizar)))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextCadConta)
                                .addGap(34, 34, 34)
                                .addComponent(TextCredor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCadastrarPessoa))
                                .addGap(18, 18, 18)
                                .addComponent(TextData))
                            .addComponent(DateChooserEmissao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextValorConta)
                            .addComponent(FieldValorConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextNumParc)
                            .addComponent(FieldNumParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TextNota)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ComboBoxNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCadastrarNota))
                            .addGap(18, 18, 18)
                            .addComponent(TextValorPago)
                            .addGap(18, 18, 18)
                            .addComponent(FieldValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnFinalizar))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPessoaActionPerformed
        
    }//GEN-LAST:event_ComboBoxPessoaActionPerformed

    private void btnCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPessoaActionPerformed
        
    }//GEN-LAST:event_btnCadastrarPessoaActionPerformed

    private void FieldValorContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldValorContaMouseClicked
        FieldValorConta.setText("");        
    }//GEN-LAST:event_FieldValorContaMouseClicked

    private void FieldNumParcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldNumParcMouseClicked
        FieldNumParc.setText("");        
    }//GEN-LAST:event_FieldNumParcMouseClicked

    private void FieldValorPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldValorPagoMouseClicked
        FieldValorPago.setText("");        
    }//GEN-LAST:event_FieldValorPagoMouseClicked

    private void FieldAcrescimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldAcrescimosMouseClicked
        FieldAcrescimos.setText("");
        
    }//GEN-LAST:event_FieldAcrescimosMouseClicked

    private void FieldValorParcelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldValorParcelaMouseClicked
              
    }//GEN-LAST:event_FieldValorParcelaMouseClicked

    private void FieldValorPagoParcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldValorPagoParcMouseClicked
        FieldValorPagoParc.setText("");        
    }//GEN-LAST:event_FieldValorPagoParcMouseClicked

    private void FieldValorContaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldValorContaFocusGained
        FieldValorConta.setText("");
        
    }//GEN-LAST:event_FieldValorContaFocusGained

    private void FieldNumParcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldNumParcFocusGained
        FieldNumParc.setText("");       
    }//GEN-LAST:event_FieldNumParcFocusGained

    private void FieldValorPagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldValorPagoFocusGained
        FieldValorPago.setText("");
    }//GEN-LAST:event_FieldValorPagoFocusGained

    private void FieldAcrescimosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldAcrescimosFocusGained
        FieldAcrescimos.setText("");
    }//GEN-LAST:event_FieldAcrescimosFocusGained

    private void FieldValorParcelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldValorParcelaFocusGained
        
    }//GEN-LAST:event_FieldValorParcelaFocusGained

    private void FieldValorPagoParcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldValorPagoParcFocusGained
        FieldValorPagoParc.setText("");
    }//GEN-LAST:event_FieldValorPagoParcFocusGained

    private void FieldNumParcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldNumParcFocusLost
        
    }//GEN-LAST:event_FieldNumParcFocusLost

    private void FieldNumParcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldNumParcMouseExited
        
    }//GEN-LAST:event_FieldNumParcMouseExited

    private void FieldNumParcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNumParcKeyReleased
        FieldValorParcela.setText("R$ " + Integer.parseInt(FieldValorConta.getText()) / Integer.parseInt(FieldNumParc.getText()));
        int p = Integer.parseInt(FieldNumParc.getText());
        if (p > 1) {
            PainelParcelas.setEnabled(true);
            TextPainelParcelas.setEnabled(true);
            TextVencimentoParc.setEnabled(true);
            DateChooserVencParc.setEnabled(true);
            TextPgtoParcelas.setEnabled(true);
            DateChooserPgtoParc.setEnabled(true);
            TextAcrescimos.setEnabled(true);
            FieldAcrescimos.setEnabled(true);
            TextContaDebito.setEnabled(true);
            ComboBoxContaDebito.setEnabled(true);
            TextValorParcela.setEnabled(true);
            FieldValorParcela.setEnabled(true);
            TextValorPagoParc.setEnabled(true);
            FieldValorPagoParc.setEnabled(true);
        }
        else {
            PainelParcelas.setEnabled(false);
            TextPainelParcelas.setEnabled(false);
            TextVencimentoParc.setEnabled(false);
            DateChooserVencParc.setEnabled(false);
            TextPgtoParcelas.setEnabled(false);
            DateChooserPgtoParc.setEnabled(false);
            TextAcrescimos.setEnabled(false);
            FieldAcrescimos.setEnabled(false);
            TextContaDebito.setEnabled(false);
            ComboBoxContaDebito.setEnabled(false);
            TextValorParcela.setEnabled(false);
            FieldValorParcela.setEnabled(false);
            TextValorPagoParc.setEnabled(false);
            FieldValorPagoParc.setEnabled(false);
        }
    }//GEN-LAST:event_FieldNumParcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxContaDebito;
    private javax.swing.JComboBox<String> ComboBoxNotaFiscal;
    private javax.swing.JComboBox<String> ComboBoxPessoa;
    private com.toedter.calendar.JDateChooser DateChooserEmissao;
    private com.toedter.calendar.JDateChooser DateChooserPgtoParc;
    private com.toedter.calendar.JDateChooser DateChooserVencParc;
    private javax.swing.JTextField FieldAcrescimos;
    private javax.swing.JTextField FieldNumParc;
    private javax.swing.JTextField FieldValorConta;
    private javax.swing.JTextField FieldValorPago;
    private javax.swing.JTextField FieldValorPagoParc;
    private javax.swing.JTextField FieldValorParcela;
    private javax.swing.JPanel PainelParcelas;
    private javax.swing.JLabel TextAcrescimos;
    private javax.swing.JLabel TextCadConta;
    private javax.swing.JLabel TextContaDebito;
    private javax.swing.JLabel TextCredor;
    private javax.swing.JLabel TextData;
    private javax.swing.JLabel TextNota;
    private javax.swing.JLabel TextNumParc;
    private javax.swing.JLabel TextPainelParcelas;
    private javax.swing.JLabel TextPgtoParcelas;
    private javax.swing.JLabel TextValorConta;
    private javax.swing.JLabel TextValorPago;
    private javax.swing.JLabel TextValorPagoParc;
    private javax.swing.JLabel TextValorParcela;
    private javax.swing.JLabel TextVencimentoParc;
    private javax.swing.JButton btnCadastrarNota;
    private javax.swing.JButton btnCadastrarPessoa;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
