package modelFinal;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CarEstTipoOperacao generated by hbm2java
 */
@Entity
@Table(name="car_est_tipo_operacao"
    ,schema="public"
)
public class CarEstTipoOperacao  implements java.io.Serializable {


     private int tpOpId;
     private String tpOpDescricao;
     private String tpOpNome;
     private int tpOpTipo;
     private Set estMovimentacaos = new HashSet(0);
     private Set carCapContases = new HashSet(0);

    public CarEstTipoOperacao() {
    }

	
    public CarEstTipoOperacao(int tpOpId, String tpOpDescricao, String tpOpNome, int tpOpTipo) {
        this.tpOpId = tpOpId;
        this.tpOpDescricao = tpOpDescricao;
        this.tpOpNome = tpOpNome;
        this.tpOpTipo = tpOpTipo;
    }
    public CarEstTipoOperacao(int tpOpId, String tpOpDescricao, String tpOpNome, int tpOpTipo, Set estMovimentacaos, Set carCapContases) {
       this.tpOpId = tpOpId;
       this.tpOpDescricao = tpOpDescricao;
       this.tpOpNome = tpOpNome;
       this.tpOpTipo = tpOpTipo;
       this.estMovimentacaos = estMovimentacaos;
       this.carCapContases = carCapContases;
    }
   
     @Id 

    
    @Column(name="tp_op_id", unique=true, nullable=false)
    public int getTpOpId() {
        return this.tpOpId;
    }
    
    public void setTpOpId(int tpOpId) {
        this.tpOpId = tpOpId;
    }

    
    @Column(name="tp_op_descricao", nullable=false, length=100)
    public String getTpOpDescricao() {
        return this.tpOpDescricao;
    }
    
    public void setTpOpDescricao(String tpOpDescricao) {
        this.tpOpDescricao = tpOpDescricao;
    }

    
    @Column(name="tp_op_nome", nullable=false, length=100)
    public String getTpOpNome() {
        return this.tpOpNome;
    }
    
    public void setTpOpNome(String tpOpNome) {
        this.tpOpNome = tpOpNome;
    }

    
    @Column(name="tp_op_tipo", nullable=false)
    public int getTpOpTipo() {
        return this.tpOpTipo;
    }
    
    public void setTpOpTipo(int tpOpTipo) {
        this.tpOpTipo = tpOpTipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carEstTipoOperacao")
    public Set getEstMovimentacaos() {
        return this.estMovimentacaos;
    }
    
    public void setEstMovimentacaos(Set estMovimentacaos) {
        this.estMovimentacaos = estMovimentacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carEstTipoOperacao")
    public Set getCarCapContases() {
        return this.carCapContases;
    }
    
    public void setCarCapContases(Set carCapContases) {
        this.carCapContases = carCapContases;
    }




}


