package modelFinal;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PatBaixa generated by hbm2java
 */
@Entity
@Table(name="pat_baixa"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="ativo_imobilizado") 
)
public class PatBaixa  implements java.io.Serializable {


     private int baixaCodigo;
     private PatAtivoImobilizado patAtivoImobilizado;
     private PatTipoBaixa patTipoBaixa;
     private Date baixaDataBaixa;

    public PatBaixa() {
    }

	
    public PatBaixa(int baixaCodigo, Date baixaDataBaixa) {
        this.baixaCodigo = baixaCodigo;
        this.baixaDataBaixa = baixaDataBaixa;
    }
    public PatBaixa(int baixaCodigo, PatAtivoImobilizado patAtivoImobilizado, PatTipoBaixa patTipoBaixa, Date baixaDataBaixa) {
       this.baixaCodigo = baixaCodigo;
       this.patAtivoImobilizado = patAtivoImobilizado;
       this.patTipoBaixa = patTipoBaixa;
       this.baixaDataBaixa = baixaDataBaixa;
    }
   
     @Id 

    
    @Column(name="baixa_codigo", unique=true, nullable=false)
    public int getBaixaCodigo() {
        return this.baixaCodigo;
    }
    
    public void setBaixaCodigo(int baixaCodigo) {
        this.baixaCodigo = baixaCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ativo_imobilizado", unique=true)
    public PatAtivoImobilizado getPatAtivoImobilizado() {
        return this.patAtivoImobilizado;
    }
    
    public void setPatAtivoImobilizado(PatAtivoImobilizado patAtivoImobilizado) {
        this.patAtivoImobilizado = patAtivoImobilizado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_baixa")
    public PatTipoBaixa getPatTipoBaixa() {
        return this.patTipoBaixa;
    }
    
    public void setPatTipoBaixa(PatTipoBaixa patTipoBaixa) {
        this.patTipoBaixa = patTipoBaixa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="baixa_data_baixa", nullable=false, length=13)
    public Date getBaixaDataBaixa() {
        return this.baixaDataBaixa;
    }
    
    public void setBaixaDataBaixa(Date baixaDataBaixa) {
        this.baixaDataBaixa = baixaDataBaixa;
    }




}


