package modelFinal;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PatDepreciacao generated by hbm2java
 */
@Entity
@Table(name="pat_depreciacao"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="categoria") 
)
public class PatDepreciacao  implements java.io.Serializable {


     private int depreciacaoCodigo;
     private EstCategoria estCategoria;
     private double depreciacaoTaxaAnual;
     private int depreciacaoVidaUtil;
     private double depreciacaoTaxaMensal;

    public PatDepreciacao() {
    }

	
    public PatDepreciacao(int depreciacaoCodigo, double depreciacaoTaxaAnual, int depreciacaoVidaUtil, double depreciacaoTaxaMensal) {
        this.depreciacaoCodigo = depreciacaoCodigo;
        this.depreciacaoTaxaAnual = depreciacaoTaxaAnual;
        this.depreciacaoVidaUtil = depreciacaoVidaUtil;
        this.depreciacaoTaxaMensal = depreciacaoTaxaMensal;
    }
    public PatDepreciacao(int depreciacaoCodigo, EstCategoria estCategoria, double depreciacaoTaxaAnual, int depreciacaoVidaUtil, double depreciacaoTaxaMensal) {
       this.depreciacaoCodigo = depreciacaoCodigo;
       this.estCategoria = estCategoria;
       this.depreciacaoTaxaAnual = depreciacaoTaxaAnual;
       this.depreciacaoVidaUtil = depreciacaoVidaUtil;
       this.depreciacaoTaxaMensal = depreciacaoTaxaMensal;
    }
   
     @Id 

    
    @Column(name="depreciacao_codigo", unique=true, nullable=false)
    public int getDepreciacaoCodigo() {
        return this.depreciacaoCodigo;
    }
    
    public void setDepreciacaoCodigo(int depreciacaoCodigo) {
        this.depreciacaoCodigo = depreciacaoCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria", unique=true)
    public EstCategoria getEstCategoria() {
        return this.estCategoria;
    }
    
    public void setEstCategoria(EstCategoria estCategoria) {
        this.estCategoria = estCategoria;
    }

    
    @Column(name="depreciacao_taxa_anual", nullable=false, precision=17, scale=17)
    public double getDepreciacaoTaxaAnual() {
        return this.depreciacaoTaxaAnual;
    }
    
    public void setDepreciacaoTaxaAnual(double depreciacaoTaxaAnual) {
        this.depreciacaoTaxaAnual = depreciacaoTaxaAnual;
    }

    
    @Column(name="depreciacao_vida_util", nullable=false)
    public int getDepreciacaoVidaUtil() {
        return this.depreciacaoVidaUtil;
    }
    
    public void setDepreciacaoVidaUtil(int depreciacaoVidaUtil) {
        this.depreciacaoVidaUtil = depreciacaoVidaUtil;
    }

    
    @Column(name="depreciacao_taxa_mensal", nullable=false, precision=17, scale=17)
    public double getDepreciacaoTaxaMensal() {
        return this.depreciacaoTaxaMensal;
    }
    
    public void setDepreciacaoTaxaMensal(double depreciacaoTaxaMensal) {
        this.depreciacaoTaxaMensal = depreciacaoTaxaMensal;
    }




}


