package modelFinal;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PatNotaFiscal generated by hbm2java
 */
@Entity
@Table(name="pat_nota_fiscal"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="pessoa") 
)
public class PatNotaFiscal  implements java.io.Serializable {


     private int notaCodigo;
     private CarPessoa carPessoa;
     private double notaValor;
     private Date notaDataEmissao;
     private String notaChaveAcesso;
     private Date notaDataEntrada;
     private Set patAtivoImobilizados = new HashSet(0);
     private Set patItemNotas = new HashSet(0);
     private Set carCapContases = new HashSet(0);
     private Set patImpostoNotaFiscals = new HashSet(0);

    public PatNotaFiscal() {
    }

	
    public PatNotaFiscal(int notaCodigo, double notaValor, Date notaDataEmissao, String notaChaveAcesso, Date notaDataEntrada) {
        this.notaCodigo = notaCodigo;
        this.notaValor = notaValor;
        this.notaDataEmissao = notaDataEmissao;
        this.notaChaveAcesso = notaChaveAcesso;
        this.notaDataEntrada = notaDataEntrada;
    }
    public PatNotaFiscal(int notaCodigo, CarPessoa carPessoa, double notaValor, Date notaDataEmissao, String notaChaveAcesso, Date notaDataEntrada, Set patAtivoImobilizados, Set patItemNotas, Set carCapContases, Set patImpostoNotaFiscals) {
       this.notaCodigo = notaCodigo;
       this.carPessoa = carPessoa;
       this.notaValor = notaValor;
       this.notaDataEmissao = notaDataEmissao;
       this.notaChaveAcesso = notaChaveAcesso;
       this.notaDataEntrada = notaDataEntrada;
       this.patAtivoImobilizados = patAtivoImobilizados;
       this.patItemNotas = patItemNotas;
       this.carCapContases = carCapContases;
       this.patImpostoNotaFiscals = patImpostoNotaFiscals;
    }
   
     @Id 

    
    @Column(name="nota_codigo", unique=true, nullable=false)
    public int getNotaCodigo() {
        return this.notaCodigo;
    }
    
    public void setNotaCodigo(int notaCodigo) {
        this.notaCodigo = notaCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa", unique=true)
    public CarPessoa getCarPessoa() {
        return this.carPessoa;
    }
    
    public void setCarPessoa(CarPessoa carPessoa) {
        this.carPessoa = carPessoa;
    }

    
    @Column(name="nota_valor", nullable=false, precision=17, scale=17)
    public double getNotaValor() {
        return this.notaValor;
    }
    
    public void setNotaValor(double notaValor) {
        this.notaValor = notaValor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nota_data_emissao", nullable=false, length=13)
    public Date getNotaDataEmissao() {
        return this.notaDataEmissao;
    }
    
    public void setNotaDataEmissao(Date notaDataEmissao) {
        this.notaDataEmissao = notaDataEmissao;
    }

    
    @Column(name="nota_chave_acesso", nullable=false, length=100)
    public String getNotaChaveAcesso() {
        return this.notaChaveAcesso;
    }
    
    public void setNotaChaveAcesso(String notaChaveAcesso) {
        this.notaChaveAcesso = notaChaveAcesso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nota_data_entrada", nullable=false, length=13)
    public Date getNotaDataEntrada() {
        return this.notaDataEntrada;
    }
    
    public void setNotaDataEntrada(Date notaDataEntrada) {
        this.notaDataEntrada = notaDataEntrada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patNotaFiscal")
    public Set getPatAtivoImobilizados() {
        return this.patAtivoImobilizados;
    }
    
    public void setPatAtivoImobilizados(Set patAtivoImobilizados) {
        this.patAtivoImobilizados = patAtivoImobilizados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patNotaFiscal")
    public Set getPatItemNotas() {
        return this.patItemNotas;
    }
    
    public void setPatItemNotas(Set patItemNotas) {
        this.patItemNotas = patItemNotas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patNotaFiscal")
    public Set getCarCapContases() {
        return this.carCapContases;
    }
    
    public void setCarCapContases(Set carCapContases) {
        this.carCapContases = carCapContases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patNotaFiscal")
    public Set getPatImpostoNotaFiscals() {
        return this.patImpostoNotaFiscals;
    }
    
    public void setPatImpostoNotaFiscals(Set patImpostoNotaFiscals) {
        this.patImpostoNotaFiscals = patImpostoNotaFiscals;
    }




}


