package modelFinal;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Saldo generated by hbm2java
 */
@Entity
@Table(name="saldo"
    ,schema="public"
)
public class Saldo  implements java.io.Serializable {


     private int saldo;
     private EstProduto estProduto;
     private int lote;
     private Date dataValidade;

    public Saldo() {
    }

	
    public Saldo(int saldo, int lote, Date dataValidade) {
        this.saldo = saldo;
        this.lote = lote;
        this.dataValidade = dataValidade;
    }
    public Saldo(int saldo, EstProduto estProduto, int lote, Date dataValidade) {
       this.saldo = saldo;
       this.estProduto = estProduto;
       this.lote = lote;
       this.dataValidade = dataValidade;
    }
   
     @Id 

    
    @Column(name="saldo", unique=true, nullable=false)
    public int getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(int saldo) {
        this.saldo = saldo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto")
    public EstProduto getEstProduto() {
        return this.estProduto;
    }
    
    public void setEstProduto(EstProduto estProduto) {
        this.estProduto = estProduto;
    }

    
    @Column(name="lote", nullable=false)
    public int getLote() {
        return this.lote;
    }
    
    public void setLote(int lote) {
        this.lote = lote;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_validade", nullable=false, length=13)
    public Date getDataValidade() {
        return this.dataValidade;
    }
    
    public void setDataValidade(Date dataValidade) {
        this.dataValidade = dataValidade;
    }




}


