package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import enumeraveis.FormaPagamento;
import enumeraveis.MeioRecebimentoPagamento;
import enumeraveis.StatusConta;
import enumeraveis.TipoConta;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * CarCapContas generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "seq_conta", sequenceName = "seq_conta",
        allocationSize = 1)
public class CarCapContas implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_conta")
    private int contaId;

    

    private double valorRecebido;
    
    @Enumerated
    private StatusConta contaStatus;

    @ManyToOne(fetch = FetchType.LAZY)
    private CarEstTipoOperacao carEstTipoOperacao;

    
    @ManyToOne
    private CarPessoa carPessoa;

    @ManyToOne
    private FlxcxOperacoes flxcxOperacoes;

    @Transient
    private String tipoOperacaoDescricao;

    @ManyToOne(fetch = FetchType.LAZY)
    private PatNotaFiscal patNotaFiscal;

    private double contaValorTotal;
    
   
    @Temporal(TemporalType.DATE)
    private Date contaDataEmissao;

    private int contaNumParcelas;

    private double contaValorPago;

    @Enumerated
    private TipoConta contaTipo;

    private String descricao;

    @ManyToOne
    private EstProduto produto;
    
    @ManyToOne
    private CarcapOperacoesComerciais carcapOperacoesComerciais;

    public EstProduto getProduto() {
        return produto;
    }

    public void setProduto(EstProduto produto) {
        this.produto = produto;
    }
    
    @Enumerated
    private FormaPagamento forma_rece_pagamento;


    @Enumerated
    private MeioRecebimentoPagamento meio_recebimento;

//    @Column(name = "forma_pagamento_receb", nullable = false)
   // private String forma_rece_pagamento;
    


    private double quantidade_produto;

    private double acrescimo;

    @Transient
    private String contaStatusDescricao;

    @Transient
    private String contaTipoDescricao;

    public double getAcrescimo() {
        return acrescimo;
    }

    public void setAcrescimo(double acrescimo) {
        this.acrescimo = acrescimo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public StatusConta getContaStatus() {
        return contaStatus;
    }

    public void setContaStatus(StatusConta contaStatus) {
        this.contaStatus = contaStatus;
    }
//    public void setProduto(String produto) {
//        this.produto = produto;
//
//    public String getPessoaNome() {
//        return pessoaNome;
//    }
    public String getTipoOperacaoDescricao() {
        return tipoOperacaoDescricao;
    }

    public void setTipoOperacaoDescricao(String tipoOperacaoDescricao) {
        this.tipoOperacaoDescricao = tipoOperacaoDescricao;
    }

//    public void setProduto(String produto) {
//        this.produto = produto;
//
//    }
    public FormaPagamento getForma_rece_pagamento() {
        return forma_rece_pagamento;
    }

    public void setForma_rece_pagamento(FormaPagamento forma_rece_pagamento) {
        this.forma_rece_pagamento = forma_rece_pagamento;
    }

    public MeioRecebimentoPagamento getMeio_recebimento() {
        return meio_recebimento;
    }

    public void setMeio_recebimento(MeioRecebimentoPagamento meio_recebimento) {
        this.meio_recebimento = meio_recebimento;
    }

    public double getQuantidade_produto() {
        return quantidade_produto;
    }

    public void setQuantidade_produto(double quantidade_produto) {
        this.quantidade_produto = quantidade_produto;

    }

//    public StatusConta getContaStatus() {
//        return contaStatus;
//    }
//
//    public void setContaStatus(StatusConta contaStatus) {
//        this.contaStatus = contaStatus;
//    }
    public String getContaStatusDescricao() {
        return contaStatusDescricao;
    }

    public void setContaStatusDescricao(String contaStatusDescricao) {
        this.contaStatusDescricao = contaStatusDescricao;
    }

    public String getContaTipoDescricao() {
        return contaTipoDescricao;
    }

    public void setContaTipoDescricao(String contaTipoDescricao) {
        this.contaTipoDescricao = contaTipoDescricao;
    }

    public CarCapContas() {
    }
    

    public CarCapContas(int contaId, double contaValorTotal, /*double valorParcela,*/  Date contaDataEmissao, int contaNumParcelas, double contaValorPago, TipoConta contaTipo, String produto, String descricao,
            MeioRecebimentoPagamento meio_recebimento, double quantidade_produto, FormaPagamento forma_rece_pagamento,double valorRecebido) {
        this.contaId = contaId;
        this.contaValorTotal = contaValorTotal;
        this.contaDataEmissao = contaDataEmissao;
        this.contaNumParcelas = contaNumParcelas;
        this.contaValorPago = contaValorPago;
        this.contaTipo = contaTipo;
        this.descricao = descricao;
        this.meio_recebimento = meio_recebimento;
        this.quantidade_produto = quantidade_produto;
        this.forma_rece_pagamento = forma_rece_pagamento;
        this.valorRecebido = valorRecebido;
       // this.valorParcela = valorParcela;
      }

    public CarCapContas(int contaId, StatusConta contaStatus,/*double valorParcela,*/ CarEstTipoOperacao carEstTipoOperacao, CarPessoa carPessoa, FlxcxOperacoes flxcxOperacoes, PatNotaFiscal patNotaFiscal, double contaValorTotal, Date contaDataEmissao, int contaNumParcelas, double contaValorPago, TipoConta contaTipo, String produto, String descricao,
            MeioRecebimentoPagamento meio_recebimento, double quantidade_produto, FormaPagamento forma_rece_pagamento,double valo) {
        this.contaId = contaId;
        this.contaStatus = contaStatus;
        this.carEstTipoOperacao = carEstTipoOperacao;
        this.carPessoa = carPessoa;
        this.flxcxOperacoes = flxcxOperacoes;
        this.patNotaFiscal = patNotaFiscal;
        this.contaValorTotal = contaValorTotal;
        this.contaDataEmissao = contaDataEmissao;
        this.contaNumParcelas = contaNumParcelas;
        this.contaValorPago = contaValorPago;
        this.contaTipo = contaTipo;
        this.descricao = descricao;
        this.meio_recebimento = meio_recebimento;
        this.quantidade_produto = quantidade_produto;
        this.forma_rece_pagamento = forma_rece_pagamento;
        this.valorRecebido = valo;
      //  this.valorParcela = valorParcela;
    }

    public int getContaId() {
        return this.contaId;
    }

    public void setContaId(int contaId) {
        this.contaId = contaId;
    }

    public StatusConta getCapContaStatus() {
        return this.contaStatus;
    }

    public void setCapContaStatus(StatusConta contaStatus) {
        this.contaStatus = contaStatus;
    }

    public CarEstTipoOperacao getCarEstTipoOperacao() {
        return this.carEstTipoOperacao;
    }

    public void setCarEstTipoOperacao(CarEstTipoOperacao carEstTipoOperacao) {
        this.carEstTipoOperacao = carEstTipoOperacao;
    }

    public CarPessoa getCarPessoa() {
        return this.carPessoa;
    }

    public void setCarPessoa(CarPessoa carPessoa) {
        this.carPessoa = carPessoa;
    }

    public FlxcxOperacoes getFlxcxOperacoes() {
        return this.flxcxOperacoes;
    }

    public void setFlxcxOperacoes(FlxcxOperacoes flxcxOperacoes) {
        this.flxcxOperacoes = flxcxOperacoes;
    }

    public PatNotaFiscal getPatNotaFiscal() {
        return this.patNotaFiscal;
    }

    public void setPatNotaFiscal(PatNotaFiscal patNotaFiscal) {
        this.patNotaFiscal = patNotaFiscal;
    }

    public double getContaValorTotal() {
        return this.contaValorTotal;
    }

    public void setContaValorTotal(double contaValorTotal) {
        this.contaValorTotal = contaValorTotal;
    }

    public Date getContaDataEmissao() {
        return this.contaDataEmissao;
    }

    public void setContaDataEmissao(Date contaDataEmissao) {
        this.contaDataEmissao = contaDataEmissao;
    }

    public int getContaNumParcelas() {
        return this.contaNumParcelas;
    }

    public void setContaNumParcelas(int contaNumParcelas) {
        this.contaNumParcelas = contaNumParcelas;
    }

    public double getContaValorPago() {
        return this.contaValorPago;
    }

    public void setContaValorPago(double contaValorPago) {
        this.contaValorPago = contaValorPago;
    }

    public TipoConta getContaTipo() {
        return this.contaTipo;
    }

    public void setContaTipo(TipoConta contaTipo) {
        this.contaTipo = contaTipo;
    }



//    public void setCarCapParcelas(Set<CarCapParcela> carCapParcelas) {
//        this.carCapParcelas = carCapParcelas;
//    }

    public CarcapOperacoesComerciais getCarcapOperacoesComerciais() {
        return carcapOperacoesComerciais;
    }

    public void setCarcapOperacoesComerciais(CarcapOperacoesComerciais carcapOperacoesComerciais) {
        this.carcapOperacoesComerciais = carcapOperacoesComerciais;
    }

   

    
//    public Set<CarCapParcela> getCarCapParcelas() {
//        return this.carCapParcelas;
//    }
//
//    public void setCarCapParcelas(Set<CarCapParcela> carCapParcelas) {
//        this.carCapParcelas = carCapParcelas;
//    }
//
//   

    public double getValorRecebido() {
        return valorRecebido;
    }

    public void setValorRecebido(double valorRecebido) {
        this.valorRecebido = valorRecebido;
    }


}
