package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CarCapParcela generated by hbm2java
 */
@Entity
@Table(name = "car_cap_parcela", schema = "public"
)
public class CarCapParcela implements java.io.Serializable {

    private int parcelaId;
    private CarCapContas carCapContas;
    private Date parcelaDataPagamento;
    private Date parcelaDataVencimento;
    private double parcelaAcrescimos;
    private double parcelaValor;
    private double parcelaValorPago;

    public CarCapParcela() {
    }

    public CarCapParcela(int parcelaId, Date parcelaDataPagamento, Date parcelaDataVencimento, double parcelaAcrescimos, double parcelaValor, double parcelaValorPago) {
        this.parcelaId = parcelaId;
        this.parcelaDataPagamento = parcelaDataPagamento;
        this.parcelaDataVencimento = parcelaDataVencimento;
        this.parcelaAcrescimos = parcelaAcrescimos;
        this.parcelaValor = parcelaValor;
        this.parcelaValorPago = parcelaValorPago;
    }

    public CarCapParcela(int parcelaId, CarCapContas carCapContas, Date parcelaDataPagamento, Date parcelaDataVencimento, double parcelaAcrescimos, double parcelaValor, double parcelaValorPago) {
        this.parcelaId = parcelaId;
        this.carCapContas = carCapContas;
        this.parcelaDataPagamento = parcelaDataPagamento;
        this.parcelaDataVencimento = parcelaDataVencimento;
        this.parcelaAcrescimos = parcelaAcrescimos;
        this.parcelaValor = parcelaValor;
        this.parcelaValorPago = parcelaValorPago;
    }

    @Id

    @Column(name = "parcela_id", unique = true, nullable = false)
    public int getParcelaId() {
        return this.parcelaId;
    }

    public void setParcelaId(int parcelaId) {
        this.parcelaId = parcelaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    public CarCapContas getCarCapContas() {
        return this.carCapContas;
    }

    public void setCarCapContas(CarCapContas carCapContas) {
        this.carCapContas = carCapContas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "parcela_data_pagamento", nullable = false, length = 13)
    public Date getParcelaDataPagamento() {
        return this.parcelaDataPagamento;
    }

    public void setParcelaDataPagamento(Date parcelaDataPagamento) {
        this.parcelaDataPagamento = parcelaDataPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "parcela_data_vencimento", nullable = false, length = 13)
    public Date getParcelaDataVencimento() {
        return this.parcelaDataVencimento;
    }

    public void setParcelaDataVencimento(Date parcelaDataVencimento) {
        this.parcelaDataVencimento = parcelaDataVencimento;
    }

    @Column(name = "parcela_acrescimos", nullable = false, precision = 17, scale = 17)
    public double getParcelaAcrescimos() {
        return this.parcelaAcrescimos;
    }

    public void setParcelaAcrescimos(double parcelaAcrescimos) {
        this.parcelaAcrescimos = parcelaAcrescimos;
    }

    @Column(name = "parcela_valor", nullable = false, precision = 17, scale = 17)
    public double getParcelaValor() {
        return this.parcelaValor;
    }

    public void setParcelaValor(double parcelaValor) {
        this.parcelaValor = parcelaValor;
    }

    @Column(name = "parcela_valor_pago", nullable = false, precision = 17, scale = 17)
    public double getParcelaValorPago() {
        return this.parcelaValorPago;
    }

    public void setParcelaValorPago(double parcelaValorPago) {
        this.parcelaValorPago = parcelaValorPago;
    }

}
