package model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * CarPessoa generated by hbm2java - editado por Dimas
 */
@Entity
@Table(name = "car_pessoa", schema = "public"
)
@SequenceGenerator(name = "seq_nome", sequenceName = "seq_nome", allocationSize = 1)
public class CarPessoa implements java.io.Serializable {
    private CarcapOperacoesComerciais carcapOperacoesComerciais;

    private int pessoaId;
    private Integer pessoaTipo;
    private String pessoaNome;
    private String pessoaCpfCnpj;
    private String pessoaFone;
    private String pessoaEmail;
    private String pessoaEndereco;
    private String pessoaComplemento;
    private String pessoaBairro;
    private String pessoaCidade;
    private String pessoaUF;
    private int pessoaCEP;
    
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_nome") 
    @Column(name = "pessoa_id", unique = true, nullable = false)
    public int getPessoaId() {
        return this.pessoaId;
    }

    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }

    @Column(name = "pessoa_nome", nullable = false, length = 100)
    public String getPessoaNome() {
        return this.pessoaNome;
    }

    public void setPessoaNome(String pessoaNome) {
        this.pessoaNome = pessoaNome;
    }

    @Column(name = "pessoa_tipo")
    public Integer getPessoaTipo() {
        return this.pessoaTipo;
    }

    public void setPessoaTipo(Integer pessoaTipo) {
        this.pessoaTipo = pessoaTipo;
    }

    @Column(name = "pessoa_endereco", length = 100)
    public String getPessoaEndereco() {
        return this.pessoaEndereco;
    }

    public void setPessoaEndereco(String pessoaEndereco) {
        this.pessoaEndereco = pessoaEndereco;
    }

    @Column(name = "pessoa_cnpj_cpf", precision = 14, scale = 0)
    public String getPessoaCnpjCpf() {
        return this.pessoaCpfCnpj;
    }

    public void setPessoaCnpjCpf(String pessoaCnpjCpf) {
        this.pessoaCpfCnpj = pessoaCnpjCpf;
    }
    
    public String getPessoaCpfCnpj() {
        return pessoaCpfCnpj;
    }

    public void setPessoaCpfCnpj(String pessoaCpfCnpj) {
        this.pessoaCpfCnpj = pessoaCpfCnpj;
    }

    public String getPessoaFone() {
        return pessoaFone;
    }

    public void setPessoaFone(String pessoaFone) {
        this.pessoaFone = pessoaFone;
    }

    public String getPessoaEmail() {
        return pessoaEmail;
    }

    public void setPessoaEmail(String pessoaEmail) {
        this.pessoaEmail = pessoaEmail;
    }

    public String getPessoaComplemento() {
        return pessoaComplemento;
    }

    public void setPessoaComplemento(String pessoaComplemento) {
        this.pessoaComplemento = pessoaComplemento;
    }

    public String getPessoaBairro() {
        return pessoaBairro;
    }

    public void setPessoaBairro(String pessoaBairro) {
        this.pessoaBairro = pessoaBairro;
    }

    public String getPessoaCidade() {
        return pessoaCidade;
    }

    public void setPessoaCidade(String pessoaCidade) {
        this.pessoaCidade = pessoaCidade;
    }

    public String getPessoaUF() {
        return pessoaUF;
    }

    public void setPessoaUF(String pessoaUF) {
        this.pessoaUF = pessoaUF;
    }

    public int getPessoaCEP() {
        return pessoaCEP;
    }

    public void setPessoaCEP(int pessoaCEP) {
        this.pessoaCEP = pessoaCEP;
    }

    
    public CarcapOperacoesComerciais getCarcapOperacoesComerciais() {
        return carcapOperacoesComerciais;
    }

    public void setCarcapOperacoesComerciais(CarcapOperacoesComerciais carcapOperacoesComerciais) {
        this.carcapOperacoesComerciais = carcapOperacoesComerciais;
    }
    
}