package model;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;

/**
 * CarPessoa generated by hbm2java - editado por Dimas
 */
@Entity
@SequenceGenerator(name = "seq_nome", sequenceName = "seq_nome", allocationSize = 1)
public class CarPessoa implements java.io.Serializable {

    private List<CarcapOperacoesComerciais> carcapOperacoesComerciais;

    private int pessoaId;
    private int pessoaTipo;
    private String pessoaNome;
    private String pessoaCpfCnpj;
    private String pessoaFone;
    private String pessoaEmail;
    private String pessoaEndereco;
    private String pessoaComplemento;
    private String pessoaBairro;
    private String pessoaCidade;
    private String pessoaUF;
    private String pessoaCEP;
    private TipoUsuario pessoaLevel;
    private String pessoaLogin;
    private String pessoaSenha;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_nome")
    public int getPessoaId() {
        return this.pessoaId;
    }

    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }

    public String getPessoaNome() {
        return this.pessoaNome;
    }

    public void setPessoaNome(String pessoaNome) {
        this.pessoaNome = pessoaNome;
    }

    public Integer getPessoaTipo() {
        return this.pessoaTipo;
    }

    public void setPessoaTipo(Integer pessoaTipo) {
        this.pessoaTipo = pessoaTipo;
    }

    public String getPessoaEndereco() {
        return this.pessoaEndereco;
    }

    public void setPessoaEndereco(String pessoaEndereco) {
        this.pessoaEndereco = pessoaEndereco;
    }

    public String getPessoaCpfCnpj() {
        return pessoaCpfCnpj;
    }

    public void setPessoaCpfCnpj(String pessoaCpfCnpj) {
        this.pessoaCpfCnpj = pessoaCpfCnpj;
    }

    public String getPessoaFone() {
        return pessoaFone;
    }

    public void setPessoaFone(String pessoaFone) {
        this.pessoaFone = pessoaFone;
    }

    public String getPessoaEmail() {
        return pessoaEmail;
    }

    public void setPessoaEmail(String pessoaEmail) {
        this.pessoaEmail = pessoaEmail;
    }

    public String getPessoaComplemento() {
        return pessoaComplemento;
    }

    public void setPessoaComplemento(String pessoaComplemento) {
        this.pessoaComplemento = pessoaComplemento;
    }

    public String getPessoaBairro() {
        return pessoaBairro;
    }

    public void setPessoaBairro(String pessoaBairro) {
        this.pessoaBairro = pessoaBairro;
    }

    public String getPessoaCidade() {
        return pessoaCidade;
    }

    public void setPessoaCidade(String pessoaCidade) {
        this.pessoaCidade = pessoaCidade;
    }

    public String getPessoaUF() {
        return pessoaUF;
    }

    public void setPessoaUF(String pessoaUF) {
        this.pessoaUF = pessoaUF;
    }

    public String getPessoaCEP() {
        return pessoaCEP;
    }

    public void setPessoaCEP(String pessoaCEP) {
        this.pessoaCEP = pessoaCEP;
    }

    @OneToMany(mappedBy = "pessoa")
    public List<CarcapOperacoesComerciais> getCarcapOperacoesComerciais() {
        return carcapOperacoesComerciais;
    }

    public void setCarcapOperacoesComerciais(List<CarcapOperacoesComerciais> carcapOperacoesComerciais) {
        this.carcapOperacoesComerciais = carcapOperacoesComerciais;
    }

    public TipoUsuario getPessoaLevel() {
        return pessoaLevel;
    }

    public void setPessoaLevel(TipoUsuario pessoaLevel) {
        this.pessoaLevel = pessoaLevel;
    }

    public String getPessoaLogin() {
        return pessoaLogin;
    }

    public void setPessoaLogin(String pessoaLogin) {
        this.pessoaLogin = pessoaLogin;
    }

    public String getPessoaSenha() {
        return pessoaSenha;
    }

    public void setPessoaSenha(String pessoaSenha) {
        this.pessoaSenha = pessoaSenha;
    }

}