package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstCategoria generated by hbm2java
 */
@Entity
@Table(name="est_categoria"
    ,schema="public"
)
public class EstCategoria  implements java.io.Serializable {


     private int categoriaId;
     private String categoriaDescricao;
     private Set estProdutos = new HashSet(0);
     private Set patDepreciacaos = new HashSet(0);
     private Set patAtivoImobilizados = new HashSet(0);

    public EstCategoria() {
    }

	
    public EstCategoria(int categoriaId, String categoriaDescricao) {
        this.categoriaId = categoriaId;
        this.categoriaDescricao = categoriaDescricao;
    }
    public EstCategoria(int categoriaId, String categoriaDescricao, Set estProdutos, Set patDepreciacaos, Set patAtivoImobilizados) {
       this.categoriaId = categoriaId;
       this.categoriaDescricao = categoriaDescricao;
       this.estProdutos = estProdutos;
       this.patDepreciacaos = patDepreciacaos;
       this.patAtivoImobilizados = patAtivoImobilizados;
    }
   
     @Id 

    
    @Column(name="categoria_id", unique=true, nullable=false)
    public int getCategoriaId() {
        return this.categoriaId;
    }
    
    public void setCategoriaId(int categoriaId) {
        this.categoriaId = categoriaId;
    }

    
    @Column(name="categoria_descricao", nullable=false, length=200)
    public String getCategoriaDescricao() {
        return this.categoriaDescricao;
    }
    
    public void setCategoriaDescricao(String categoriaDescricao) {
        this.categoriaDescricao = categoriaDescricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estCategoria")
    public Set getEstProdutos() {
        return this.estProdutos;
    }
    
    public void setEstProdutos(Set estProdutos) {
        this.estProdutos = estProdutos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estCategoria")
    public Set getPatDepreciacaos() {
        return this.patDepreciacaos;
    }
    
    public void setPatDepreciacaos(Set patDepreciacaos) {
        this.patDepreciacaos = patDepreciacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estCategoria")
    public Set getPatAtivoImobilizados() {
        return this.patAtivoImobilizados;
    }
    
    public void setPatAtivoImobilizados(Set patAtivoImobilizados) {
        this.patAtivoImobilizados = patAtivoImobilizados;
    }




}


