package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstSaldo generated by hbm2java
 */
@Entity
public class EstSaldo implements java.io.Serializable {

    private int saldo;
    private EstProduto estProduto;
    private int lote;
    private Date dataValidade;

    public EstSaldo() {
    }

    public EstSaldo(int saldo, int lote, Date dataValidade) {
        this.saldo = saldo;
        this.lote = lote;
        this.dataValidade = dataValidade;
    }

    public EstSaldo(int saldo, EstProduto estProduto, int lote, Date dataValidade) {
        this.saldo = saldo;
        this.estProduto = estProduto;
        this.lote = lote;
        this.dataValidade = dataValidade;
    }

    @Id

    public int getSaldo() {
        return this.saldo;
    }

    public void setSaldo(int saldo) {
        this.saldo = saldo;
    }

    @ManyToOne(fetch = FetchType.LAZY)

    public EstProduto getEstProduto() {
        return this.estProduto;
    }

    public void setEstProduto(EstProduto estProduto) {
        this.estProduto = estProduto;
    }

    public int getLote() {
        return this.lote;
    }

    public void setLote(int lote) {
        this.lote = lote;
    }

    @Temporal(TemporalType.DATE)
    public Date getDataValidade() {
        return this.dataValidade;
    }

    public void setDataValidade(Date dataValidade) {
        this.dataValidade = dataValidade;
    }

}
