package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstUnidadeMedida generated by hbm2java
 */
@Entity
@Table(name = "est_unidade_medida", schema = "public"
)
public class EstUnidadeMedida implements java.io.Serializable {

    private int unidadeMedidaId;
    private String unidadeMedidaDescricao;
    private Set<EstProduto> estProdutos = new HashSet(0);

    public EstUnidadeMedida() {
    }

    public EstUnidadeMedida(int unidadeMedidaId, String unidadeMedidaDescricao) {
        this.unidadeMedidaId = unidadeMedidaId;
        this.unidadeMedidaDescricao = unidadeMedidaDescricao;
    }

    public EstUnidadeMedida(int unidadeMedidaId, String unidadeMedidaDescricao, Set<EstProduto> estProdutos) {
        this.unidadeMedidaId = unidadeMedidaId;
        this.unidadeMedidaDescricao = unidadeMedidaDescricao;
        this.estProdutos = estProdutos;
    }

    @Id

    @Column(name = "unidade_medida_id", unique = true, nullable = false)
    public int getUnidadeMedidaId() {
        return this.unidadeMedidaId;
    }

    public void setUnidadeMedidaId(int unidadeMedidaId) {
        this.unidadeMedidaId = unidadeMedidaId;
    }

    @Column(name = "unidade_medida_descricao", nullable = false, length = 200)
    public String getUnidadeMedidaDescricao() {
        return this.unidadeMedidaDescricao;
    }

    public void setUnidadeMedidaDescricao(String unidadeMedidaDescricao) {
        this.unidadeMedidaDescricao = unidadeMedidaDescricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estUnidadeMedida")
    public Set<EstProduto> getEstProdutos() {
        return this.estProdutos;
    }

    public void setEstProdutos(Set<EstProduto> estProdutos) {
        this.estProdutos = estProdutos;
    }

}
