package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlxcxEspFluxoCaixa generated by hbm2java
 */
@Entity
@Table(name="flxcx_esp_fluxo_caixa"
    ,schema="public"
)
public class FlxcxEspFluxoCaixa  implements java.io.Serializable {


     private FlxcxEspFluxoCaixaId id;
     private FlxcxEspecificacoes flxcxEspecificacoes;
     private FlxcxFluxoCaixa flxcxFluxoCaixa;
     private Date espFluxData;

    public FlxcxEspFluxoCaixa() {
    }

	
    public FlxcxEspFluxoCaixa(FlxcxEspFluxoCaixaId id, FlxcxEspecificacoes flxcxEspecificacoes, FlxcxFluxoCaixa flxcxFluxoCaixa) {
        this.id = id;
        this.flxcxEspecificacoes = flxcxEspecificacoes;
        this.flxcxFluxoCaixa = flxcxFluxoCaixa;
    }
    public FlxcxEspFluxoCaixa(FlxcxEspFluxoCaixaId id, FlxcxEspecificacoes flxcxEspecificacoes, FlxcxFluxoCaixa flxcxFluxoCaixa, Date espFluxData) {
       this.id = id;
       this.flxcxEspecificacoes = flxcxEspecificacoes;
       this.flxcxFluxoCaixa = flxcxFluxoCaixa;
       this.espFluxData = espFluxData;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="espCodigo", column=@Column(name="esp_codigo", nullable=false) ), 
        @AttributeOverride(name="fluxCodigo", column=@Column(name="flux_codigo", nullable=false) ) } )
    public FlxcxEspFluxoCaixaId getId() {
        return this.id;
    }
    
    public void setId(FlxcxEspFluxoCaixaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="esp_codigo", nullable=false, insertable=false, updatable=false)
    public FlxcxEspecificacoes getFlxcxEspecificacoes() {
        return this.flxcxEspecificacoes;
    }
    
    public void setFlxcxEspecificacoes(FlxcxEspecificacoes flxcxEspecificacoes) {
        this.flxcxEspecificacoes = flxcxEspecificacoes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="flux_codigo", nullable=false, insertable=false, updatable=false)
    public FlxcxFluxoCaixa getFlxcxFluxoCaixa() {
        return this.flxcxFluxoCaixa;
    }
    
    public void setFlxcxFluxoCaixa(FlxcxFluxoCaixa flxcxFluxoCaixa) {
        this.flxcxFluxoCaixa = flxcxFluxoCaixa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="esp_flux_data", length=13)
    public Date getEspFluxData() {
        return this.espFluxData;
    }
    
    public void setEspFluxData(Date espFluxData) {
        this.espFluxData = espFluxData;
    }




}


