package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FlxcxEspecificacoes generated by hbm2java
 */
@Entity
@Table(name = "flxcx_especificacoes", schema = "public"
)
public class FlxcxEspecificacoes implements java.io.Serializable {

    private int espCodigo;
    private String espDescricao;
    private Integer espCodigoPai;
    private List<FlxcxOperacoes> operacao;
    

    public FlxcxEspecificacoes() {
    }

    public FlxcxEspecificacoes(int espCodigo) {
        this.espCodigo = espCodigo;
    }

    public FlxcxEspecificacoes(int espCodigo, String espDescricao, Integer espCodigoPai) {
        this.espCodigo = espCodigo;
        this.espDescricao = espDescricao;
        this.espCodigoPai = espCodigoPai;
    }

    @Id

    @Column(name = "esp_codigo", unique = true, nullable = false)
    public int getEspCodigo() {
        return this.espCodigo;
    }

    public void setEspCodigo(int espCodigo) {
        this.espCodigo = espCodigo;
    }

    @Column(name = "esp_descricao", length = 250)
    public String getEspDescricao() {
        return this.espDescricao;
    }

    public void setEspDescricao(String espDescricao) {
        this.espDescricao = espDescricao;
    }

    @Column(name = "esp_codigo_pai")
    public Integer getEspCodigoPai() {
        return this.espCodigoPai;
    }

    public void setEspCodigoPai(Integer espCodigoPai) {
        this.espCodigoPai = espCodigoPai;
    }

    @OneToMany(mappedBy = "flxcxEspecificacoes")
    public List<FlxcxOperacoes> getOperacao() {
        return operacao;
    }

    public void setOperacao(List<FlxcxOperacoes> operacao) {
        this.operacao = operacao;
    }
   
    
    
    
}
