package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FlxcxEspecificacoes generated by hbm2java
 */
@Entity
@Table(name="flxcx_especificacoes"
    ,schema="public"
)
public class FlxcxEspecificacoes  implements java.io.Serializable {


     private int espCodigo;
     private String espDescricao;
     private Integer espCodigoPai;
     private Set carCapContases = new HashSet(0);
     private Set flxcxMovimentoBancarios = new HashSet(0);
     private Set flxcxEspFluxoCaixas = new HashSet(0);

    public FlxcxEspecificacoes() {
    }

	
    public FlxcxEspecificacoes(int espCodigo) {
        this.espCodigo = espCodigo;
    }
    public FlxcxEspecificacoes(int espCodigo, String espDescricao, Integer espCodigoPai, Set carCapContases, Set flxcxMovimentoBancarios, Set flxcxEspFluxoCaixas) {
       this.espCodigo = espCodigo;
       this.espDescricao = espDescricao;
       this.espCodigoPai = espCodigoPai;
       this.carCapContases = carCapContases;
       this.flxcxMovimentoBancarios = flxcxMovimentoBancarios;
       this.flxcxEspFluxoCaixas = flxcxEspFluxoCaixas;
    }
   
     @Id 

    
    @Column(name="esp_codigo", unique=true, nullable=false)
    public int getEspCodigo() {
        return this.espCodigo;
    }
    
    public void setEspCodigo(int espCodigo) {
        this.espCodigo = espCodigo;
    }

    
    @Column(name="esp_descricao", length=250)
    public String getEspDescricao() {
        return this.espDescricao;
    }
    
    public void setEspDescricao(String espDescricao) {
        this.espDescricao = espDescricao;
    }

    
    @Column(name="esp_codigo_pai")
    public Integer getEspCodigoPai() {
        return this.espCodigoPai;
    }
    
    public void setEspCodigoPai(Integer espCodigoPai) {
        this.espCodigoPai = espCodigoPai;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="flxcx_contas_especificacoes", schema="public", joinColumns = { 
        @JoinColumn(name="esp_codigo_flxcx_especificacoes", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="conta_id_car_cap_contas", nullable=false, updatable=false) })
    public Set getCarCapContases() {
        return this.carCapContases;
    }
    
    public void setCarCapContases(Set carCapContases) {
        this.carCapContases = carCapContases;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="flxcxEspecificacoeses")
    public Set getFlxcxMovimentoBancarios() {
        return this.flxcxMovimentoBancarios;
    }
    
    public void setFlxcxMovimentoBancarios(Set flxcxMovimentoBancarios) {
        this.flxcxMovimentoBancarios = flxcxMovimentoBancarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="flxcxEspecificacoes")
    public Set getFlxcxEspFluxoCaixas() {
        return this.flxcxEspFluxoCaixas;
    }
    
    public void setFlxcxEspFluxoCaixas(Set flxcxEspFluxoCaixas) {
        this.flxcxEspFluxoCaixas = flxcxEspFluxoCaixas;
    }




}


