package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlxcxEspFluxoCaixaId generated by hbm2java
 */
@Embeddable
public class FlxcxEspFluxoCaixaId  implements java.io.Serializable {


     private int espCodigo;
     private int fluxCodigo;

    public FlxcxEspFluxoCaixaId() {
    }

    public FlxcxEspFluxoCaixaId(int espCodigo, int fluxCodigo) {
       this.espCodigo = espCodigo;
       this.fluxCodigo = fluxCodigo;
    }
   


    @Column(name="esp_codigo", nullable=false)
    public int getEspCodigo() {
        return this.espCodigo;
    }
    
    public void setEspCodigo(int espCodigo) {
        this.espCodigo = espCodigo;
    }


    @Column(name="flux_codigo", nullable=false)
    public int getFluxCodigo() {
        return this.fluxCodigo;
    }
    
    public void setFluxCodigo(int fluxCodigo) {
        this.fluxCodigo = fluxCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FlxcxEspFluxoCaixaId) ) return false;
		 FlxcxEspFluxoCaixaId castOther = ( FlxcxEspFluxoCaixaId ) other; 
         
		 return (this.getEspCodigo()==castOther.getEspCodigo())
 && (this.getFluxCodigo()==castOther.getFluxCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEspCodigo();
         result = 37 * result + this.getFluxCodigo();
         return result;
   }   


}


