package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * FlxcxTributacao generated by hbm2java
 */
@Entity
@Table(name="flxcx_tributacao"
    ,schema="public"
)
public class FlxcxTributacao  implements java.io.Serializable {


     private int tribCodigo;
     private String tribDescricao;
     private Set flxcxOperacoeses = new HashSet(0);

    public FlxcxTributacao() {
    }

	
    public FlxcxTributacao(int tribCodigo) {
        this.tribCodigo = tribCodigo;
    }
    public FlxcxTributacao(int tribCodigo, String tribDescricao, Set flxcxOperacoeses) {
       this.tribCodigo = tribCodigo;
       this.tribDescricao = tribDescricao;
       this.flxcxOperacoeses = flxcxOperacoeses;
    }
   
     @Id 

    
    @Column(name="trib_codigo", unique=true, nullable=false)
    public int getTribCodigo() {
        return this.tribCodigo;
    }
    
    public void setTribCodigo(int tribCodigo) {
        this.tribCodigo = tribCodigo;
    }

    
    @Column(name="trib_descricao", length=20)
    public String getTribDescricao() {
        return this.tribDescricao;
    }
    
    public void setTribDescricao(String tribDescricao) {
        this.tribDescricao = tribDescricao;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="flxcxTributacaos")
    public Set getFlxcxOperacoeses() {
        return this.flxcxOperacoeses;
    }
    
    public void setFlxcxOperacoeses(Set flxcxOperacoeses) {
        this.flxcxOperacoeses = flxcxOperacoeses;
    }




}


