package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlxcxLivroCaixa generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "flxcxcodigo", sequenceName = "flxcxcodigo", allocationSize = 1)
@Table(name = "flxcx_livro_caixa", schema = "public"
)
public class FlxcxLivroCaixa implements Serializable {

    private int lvrCxCodigo;
    private BigDecimal lvrCxSaldoAnterior;
    private BigDecimal lvrCxSaldoAtual;
    private BigDecimal lvrCxTotalEntrada;
    private BigDecimal lvrCxTotalSaida;
    private Date lvrCxDataInicial;
    private Date lvrCxDataFinal;

    public FlxcxLivroCaixa() {
    }

    public FlxcxLivroCaixa(int lvrCxCodigo) {
        this.lvrCxCodigo = lvrCxCodigo;
    }

    public FlxcxLivroCaixa(int lvrCxCodigo, BigDecimal lvrCxSaldoAnterior, BigDecimal lvrCxSaldoAtual, BigDecimal lvrCxTotalEntrada, BigDecimal lvrCxTotalSaida, Date lvrCxDataInicial, Date lvrCxDataFinal) {
        this.lvrCxCodigo = lvrCxCodigo;
        this.lvrCxSaldoAnterior = lvrCxSaldoAnterior;
        this.lvrCxSaldoAtual = lvrCxSaldoAtual;
        this.lvrCxTotalEntrada = lvrCxTotalEntrada;
        this.lvrCxTotalSaida = lvrCxTotalSaida;
        this.lvrCxDataInicial = lvrCxDataInicial;
        this.lvrCxDataFinal = lvrCxDataFinal;
    }

    @Id

    @Column(name = "lvr_cx_codigo", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "flxcxcodigo")
    public int getLvrCxCodigo() {
        return this.lvrCxCodigo;
    }

    public void setLvrCxCodigo(int lvrCxCodigo) {
        this.lvrCxCodigo = lvrCxCodigo;
    }

    @Column(name = "lvr_cx_saldo_anterior", precision = 14)
    public BigDecimal getLvrCxSaldoAnterior() {
        return this.lvrCxSaldoAnterior;
    }

    public void setLvrCxSaldoAnterior(BigDecimal lvrCxSaldoAnterior) {
        this.lvrCxSaldoAnterior = lvrCxSaldoAnterior;
    }

    @Column(name = "lvr_cx_saldo_atual", precision = 14)
    public BigDecimal getLvrCxSaldoAtual() {
        return this.lvrCxSaldoAtual;
    }

    public void setLvrCxSaldoAtual(BigDecimal lvrCxSaldoAtual) {
        this.lvrCxSaldoAtual = lvrCxSaldoAtual;
    }

    @Column(name = "lvr_cx_total_entrada", precision = 14)
    public BigDecimal getLvrCxTotalEntrada() {
        return this.lvrCxTotalEntrada;
    }

    public void setLvrCxTotalEntrada(BigDecimal lvrCxTotalEntrada) {
        this.lvrCxTotalEntrada = lvrCxTotalEntrada;
    }

    @Column(name = "lvr_cx_total_saida", precision = 14)
    public BigDecimal getLvrCxTotalSaida() {
        return this.lvrCxTotalSaida;
    }

    public void setLvrCxTotalSaida(BigDecimal lvrCxTotalSaida) {
        this.lvrCxTotalSaida = lvrCxTotalSaida;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lvr_cx_data_inicial", length = 13)
    public Date getLvrCxDataInicial() {
        return this.lvrCxDataInicial;
    }

    public void setLvrCxDataInicial(Date lvrCxDataInicial) {
        this.lvrCxDataInicial = lvrCxDataInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lvr_cx_data_final", length = 13)
    public Date getLvrCxDataFinal() {
        return this.lvrCxDataFinal;
    }

    public void setLvrCxDataFinal(Date lvrCxDataFinal) {
        this.lvrCxDataFinal = lvrCxDataFinal;
    }

}
