package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PatImposto generated by hbm2java
 */
@Entity
@Table(name="pat_imposto"
    ,schema="public"
)
public class PatImposto  implements java.io.Serializable {


     private int impostoCodigo;
     private String impostoNome;
     private double impostoAliquota;
     private Set patImpostoItemNotas = new HashSet(0);
     private Set patImpostoNotaFiscals = new HashSet(0);

    public PatImposto() {
    }

	
    public PatImposto(int impostoCodigo, String impostoNome, double impostoAliquota) {
        this.impostoCodigo = impostoCodigo;
        this.impostoNome = impostoNome;
        this.impostoAliquota = impostoAliquota;
    }
    public PatImposto(int impostoCodigo, String impostoNome, double impostoAliquota, Set patImpostoItemNotas, Set patImpostoNotaFiscals) {
       this.impostoCodigo = impostoCodigo;
       this.impostoNome = impostoNome;
       this.impostoAliquota = impostoAliquota;
       this.patImpostoItemNotas = patImpostoItemNotas;
       this.patImpostoNotaFiscals = patImpostoNotaFiscals;
    }
   
     @Id 

    
    @Column(name="imposto_codigo", unique=true, nullable=false)
    public int getImpostoCodigo() {
        return this.impostoCodigo;
    }
    
    public void setImpostoCodigo(int impostoCodigo) {
        this.impostoCodigo = impostoCodigo;
    }

    
    @Column(name="imposto_nome", nullable=false, length=100)
    public String getImpostoNome() {
        return this.impostoNome;
    }
    
    public void setImpostoNome(String impostoNome) {
        this.impostoNome = impostoNome;
    }

    
    @Column(name="imposto_aliquota", nullable=false, precision=17, scale=17)
    public double getImpostoAliquota() {
        return this.impostoAliquota;
    }
    
    public void setImpostoAliquota(double impostoAliquota) {
        this.impostoAliquota = impostoAliquota;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patImposto")
    public Set getPatImpostoItemNotas() {
        return this.patImpostoItemNotas;
    }
    
    public void setPatImpostoItemNotas(Set patImpostoItemNotas) {
        this.patImpostoItemNotas = patImpostoItemNotas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patImposto")
    public Set getPatImpostoNotaFiscals() {
        return this.patImpostoNotaFiscals;
    }
    
    public void setPatImpostoNotaFiscals(Set patImpostoNotaFiscals) {
        this.patImpostoNotaFiscals = patImpostoNotaFiscals;
    }




}


