package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PatItemNota generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "seq_item_nota", sequenceName = "seq_item_nota", allocationSize = 1)
@Table(name = "pat_item_nota", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "produto"))
public class PatItemNota implements java.io.Serializable {

    private int itemNotaCodigo;
    private EstProduto estProduto;
    private PatNotaFiscal patNotaFiscal;
    private int itemNotaQuantidade;
    private double itemNotaValorUnitario;
    private double itemNotaValorTotal;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_item_nota")
    @Column(name = "item_nota_codigo", unique = true, nullable = false)
    public int getItemNotaCodigo() {
        return this.itemNotaCodigo;
    }

    public void setItemNotaCodigo(int itemNotaCodigo) {
        this.itemNotaCodigo = itemNotaCodigo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "produto", unique = true)
    public EstProduto getEstProduto() {
        return this.estProduto;
    }

    public void setEstProduto(EstProduto estProduto) {
        this.estProduto = estProduto;
    }

    @ManyToOne(cascade = CascadeType.PERSIST, fetch = FetchType.LAZY)
    @JoinColumn(name = "nota_fiscal")
    public PatNotaFiscal getPatNotaFiscal() {
        return this.patNotaFiscal;
    }

    public void setPatNotaFiscal(PatNotaFiscal patNotaFiscal) {
        this.patNotaFiscal = patNotaFiscal;
    }

    @Column(name = "item_nota_quantidade", nullable = false)
    public int getItemNotaQuantidade() {
        return this.itemNotaQuantidade;
    }

    public void setItemNotaQuantidade(int itemNotaQuantidade) {
        this.itemNotaQuantidade = itemNotaQuantidade;
    }

    @Column(name = "item_nota_valor_unitario", nullable = false, precision = 17, scale = 17)
    public double getItemNotaValorUnitario() {
        return this.itemNotaValorUnitario;
    }

    public void setItemNotaValorUnitario(double itemNotaValorUnitario) {
        this.itemNotaValorUnitario = itemNotaValorUnitario;
    }

    @Column(name = "item_nota_valor_total", nullable = false, precision = 17, scale = 17)
    public double getItemNotaValorTotal() {
        return this.itemNotaValorTotal;
    }

    public void setItemNotaValorTotal(double itemNotaValorTotal) {
        this.itemNotaValorTotal = itemNotaValorTotal;
    }

}
