package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatImpostoItemNota generated by hbm2java
 */
@Entity
@Table(name = "pat_imposto_item_nota", schema = "public"
)
public class PatImpostoItemNota implements java.io.Serializable {

    private int impostoItemNotaCodigo;
    private PatImposto patImposto;
    private PatItemNota patItemNota;
    private double impostoItemNotaValorImposto;

    public PatImpostoItemNota() {
    }

    public PatImpostoItemNota(int impostoItemNotaCodigo, double impostoItemNotaValorImposto) {
        this.impostoItemNotaCodigo = impostoItemNotaCodigo;
        this.impostoItemNotaValorImposto = impostoItemNotaValorImposto;
    }

    public PatImpostoItemNota(int impostoItemNotaCodigo, PatImposto patImposto, PatItemNota patItemNota, double impostoItemNotaValorImposto) {
        this.impostoItemNotaCodigo = impostoItemNotaCodigo;
        this.patImposto = patImposto;
        this.patItemNota = patItemNota;
        this.impostoItemNotaValorImposto = impostoItemNotaValorImposto;
    }

    @Id
    public int getImpostoItemNotaCodigo() {
        return this.impostoItemNotaCodigo;
    }

    public void setImpostoItemNotaCodigo(int impostoItemNotaCodigo) {
        this.impostoItemNotaCodigo = impostoItemNotaCodigo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    public PatImposto getPatImposto() {
        return this.patImposto;
    }

    public void setPatImposto(PatImposto patImposto) {
        this.patImposto = patImposto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    public PatItemNota getPatItemNota() {
        return this.patItemNota;
    }

    public void setPatItemNota(PatItemNota patItemNota) {
        this.patItemNota = patItemNota;
    }

    public double getImpostoItemNotaValorImposto() {
        return this.impostoItemNotaValorImposto;
    }

    public void setImpostoItemNotaValorImposto(double impostoItemNotaValorImposto) {
        this.impostoItemNotaValorImposto = impostoItemNotaValorImposto;
    }

}
