package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PatImposto generated by hbm2java
 */
@Entity
@Table(name = "pat_imposto", schema = "public"
)
public class PatImposto implements java.io.Serializable {

    private int impostoCodigo;
    private String impostoNome;
    private double impostoAliquota;
    private Set<PatImpostoItemNota> patImpostoItemNotas = new HashSet(0);
    private Set<PatImpostoNotaFiscal> patImpostoNotaFiscals = new HashSet(0);

    public PatImposto() {
    }

    public PatImposto(int impostoCodigo, String impostoNome, double impostoAliquota) {
        this.impostoCodigo = impostoCodigo;
        this.impostoNome = impostoNome;
        this.impostoAliquota = impostoAliquota;
    }

    public PatImposto(int impostoCodigo, String impostoNome, double impostoAliquota, Set<PatImpostoItemNota> patImpostoItemNotas, Set<PatImpostoNotaFiscal> patImpostoNotaFiscals) {
        this.impostoCodigo = impostoCodigo;
        this.impostoNome = impostoNome;
        this.impostoAliquota = impostoAliquota;
        this.patImpostoItemNotas = patImpostoItemNotas;
        this.patImpostoNotaFiscals = patImpostoNotaFiscals;
    }

    @Id

    public int getImpostoCodigo() {
        return this.impostoCodigo;
    }

    public void setImpostoCodigo(int impostoCodigo) {
        this.impostoCodigo = impostoCodigo;
    }

    public String getImpostoNome() {
        return this.impostoNome;
    }

    public void setImpostoNome(String impostoNome) {
        this.impostoNome = impostoNome;
    }

    public double getImpostoAliquota() {
        return this.impostoAliquota;
    }

    public void setImpostoAliquota(double impostoAliquota) {
        this.impostoAliquota = impostoAliquota;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "patImposto")
    public Set<PatImpostoItemNota> getPatImpostoItemNotas() {
        return this.patImpostoItemNotas;
    }

    public void setPatImpostoItemNotas(Set<PatImpostoItemNota> patImpostoItemNotas) {
        this.patImpostoItemNotas = patImpostoItemNotas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "patImposto")
    public Set<PatImpostoNotaFiscal> getPatImpostoNotaFiscals() {
        return this.patImpostoNotaFiscals;
    }

    public void setPatImpostoNotaFiscals(Set<PatImpostoNotaFiscal> patImpostoNotaFiscals) {
        this.patImpostoNotaFiscals = patImpostoNotaFiscals;
    }

}
