package model;
// Generated 22/10/2016 10:09:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PatTipoBaixa generated by hbm2java
 */
@Entity
@Table(name="pat_tipo_baixa"
    ,schema="public"
)
public class PatTipoBaixa  implements java.io.Serializable {


     private int tipoBaixaCodigo;
     private String tipoBaixaDescricao;
     private Set patBaixas = new HashSet(0);

    public PatTipoBaixa() {
    }

	
    public PatTipoBaixa(int tipoBaixaCodigo, String tipoBaixaDescricao) {
        this.tipoBaixaCodigo = tipoBaixaCodigo;
        this.tipoBaixaDescricao = tipoBaixaDescricao;
    }
    public PatTipoBaixa(int tipoBaixaCodigo, String tipoBaixaDescricao, Set patBaixas) {
       this.tipoBaixaCodigo = tipoBaixaCodigo;
       this.tipoBaixaDescricao = tipoBaixaDescricao;
       this.patBaixas = patBaixas;
    }
   
     @Id 

    
    @Column(name="tipo_baixa_codigo", unique=true, nullable=false)
    public int getTipoBaixaCodigo() {
        return this.tipoBaixaCodigo;
    }
    
    public void setTipoBaixaCodigo(int tipoBaixaCodigo) {
        this.tipoBaixaCodigo = tipoBaixaCodigo;
    }

    
    @Column(name="tipo_baixa_descricao", nullable=false, length=200)
    public String getTipoBaixaDescricao() {
        return this.tipoBaixaDescricao;
    }
    
    public void setTipoBaixaDescricao(String tipoBaixaDescricao) {
        this.tipoBaixaDescricao = tipoBaixaDescricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patTipoBaixa")
    public Set getPatBaixas() {
        return this.patBaixas;
    }
    
    public void setPatBaixas(Set patBaixas) {
        this.patBaixas = patBaixas;
    }




}


